name: slidy_calendar
description: Calendar widget for flutter that is swipeable. This widget can help you build customizable calendar with scrollable actions.
version: 1.5.2

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  effective_dart: ^1.3.0
  intl: ">=0.1.0 <0.17.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: 
